# Generated by Django 5.1.6 on 2025-03-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_customuser_is_varified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_varified',
            new_name='is_verified',
        ),
    ]
