# Generated by Django 5.1.6 on 2025-03-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_rename_is_varified_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_ott',
            field=models.TextField(blank=True, max_length=7, null=True),
        ),
    ]
