# Generated by Django 5.1.6 on 2025-03-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menus', '0002_rename_menu_category_id_menuitem_menu_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='menu_category',
            new_name='MenuCategory_id',
        ),
    ]
