# Generated by Django 5.1.6 on 2025-03-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menus', '0004_alter_menucategory_options_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
