# Generated by Django 5.1.6 on 2025-03-12 00:56

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Menus', '0005_alter_menuitem_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_list_item_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.CharField(max_length=25)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Placed', max_length=20)),
                ('item_list_order_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(default='UserDeleted', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_add_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('count', models.IntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('menu_category', models.ForeignKey(default='CategoryNotListed', on_delete=django.db.models.deletion.SET_DEFAULT, to='Menus.menucategory')),
                ('menu_item', models.ForeignKey(default='ItemNotListed', on_delete=django.db.models.deletion.SET_DEFAULT, to='Menus.menuitem')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.orderdetail')),
            ],
        ),
    ]
